[package]
name = "hom-provider-codex-oauth"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
futures-util.workspace = true
hom-provider-base = { path = "../hom-provider-base" }
serde_json.workspace = true
tokio.workspace = true
